version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
  
  backend:
    build: ./techdome-backend
    ports:
      - "5000:5000"
    environment:
      - DB=mongodb+srv://rohit-admin:admin@123@rohit.cskvl.mongodb.net
      
      - JWT_SECRET=saptsagare2020
 
    depends_on:
      - db
    networks:
      - app-network
  
  db:
    image: mongo:6.0.17
    environment:
      MONGO_INITDB_ROOT_USERNAME: rohit-admin
      MONGO_INITDB_ROOT_PASSWORD: admin@123
      MONGO_INITDB_DATABASE: jobfind_DB
    ports:
      - "27017:27017"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
